<?php

namespace MoviePortalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActorRepository extends EntityRepository
{
    public function searchActors($string)
    {
        $query = $this->getEntityManager()->createQuery("SELECT a FROM MoviePortalBundle:Actor a WHERE a.name LIKE :string 
        OR a.surname LIKE :string");
        $query->setParameter('string',$string);
        return $query->getResult();
    }
}
