<?php

namespace MoviePortalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DirectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectorRepository extends EntityRepository
{
    public function searchDirectors($string)
    {
        $query = $this->getEntityManager()->createQuery("SELECT d FROM MoviePortalBundle:Director d WHERE d.name LIKE :string 
        OR d.surname LIKE :string");
        $query->setParameter('string',$string);
        return $query->getResult();
    }
}
