<?php

namespace MoviePortalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends EntityRepository
{
    public function searchGenres($string)
    {
        $query = $this->getEntityManager()->createQuery("SELECT g FROM MoviePortalBundle:Genre g WHERE g.name LIKE :string");
        $query->setParameter('string',$string);
        return $query->getResult();
    }
}
