<?php

namespace MoviePortalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
    public function searchMovieDatabase($string)
    {
        $em = $this->getEntityManager();
        $repository = $em->getRepository('MoviePortalBundle:Movie');
        $query = $repository->createQueryBuilder('m')
            ->innerJoin('m.actors', 'a')
            ->innerJoin('m.director', 'd')
            ->innerJoin('m.genre', 'g')
            ->innerJoin('m.writers', 'w')
            ->where('m.title LIKE :string')
            ->orWhere('a.surname LIKE :string')
            ->orWhere('d.surname LIKE :string')
            ->orWhere('g.name LIKE :string')
            ->orWhere('w.surname LIKE :string')
            ->setParameter('string', '%'.$string.'%');

        return $query->getQuery()->getResult();
    }
}
