<?php

namespace MoviePortalBundle\Repository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchMovieDatabase($string)
    {
        $query = $this->getEntityManager()->createQuery("SELECT m FROM MoviePortalBundle:Movie m WHERE m.title LIKE :string 
        OR m.director LIKE :string OR m.writers LIKE :string OR m.actor LIKE :string OR m.genre LIKE :string");
        $query->setParameter('string',$string);
        return $query->getResult();
    }
}
