<?php

namespace MoviePortalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends EntityRepository
{

    public function getRatingByMovieAndUser($movie, $user)
    {
        $query = $this->getEntityManager()->createQuery("SELECT r FROM MoviePortalBundle:Rating r WHERE r.movies = :movie AND r.user = :user");
        $query->setParameter('movie', $movie);
        $query->setParameter('user', $user);
        return $query->getResult();
    }

    public function showAllRatingsByUser($user)
    {
        $query = $this->getEntityManager()->createQuery("SELECT r FROM MoviePortalBundle:Rating r WHERE r.user = :user");
        $query->setParameter('user', $user);
        return $query->getResult();
    }
}
