<?php

namespace MoviePortalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends EntityRepository
{

    public function getRatingByMovie($movie){
        $query = $this->getEntityManager()->createQuery("SELECT avg(r.score) FROM MoviePortalBundle:Rating r WHERE r.movies LIKE :movie");
        $query->setParameter('string',$movie);
        return $query->getResult();
    }
}
