<?php

namespace MoviePortalBundle\Repository;

/**
 * WritersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WritersRepository extends \Doctrine\ORM\EntityRepository
{
}
